spring:
  application:
    name: internship-management
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/internship_management}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    open-in-view: false
